#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#author zhangjie
import json
import os,sys

parentdir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,parentdir)

from nose.tools import *

import synbot_env

import test_operate_env_A
import test_operate_env_B

test_operate_env_A.set()
print test_operate_env_B.get()


'frozenset': <type 'frozenset'>, 
'__name__': '__builtin__', 
'ord': <built-in function ord>, 
'super': <type 'super'>, 
'TypeError': <type 'exceptions.TypeError'>, 
'license': Type license() to see the full license text, 
'KeyboardInterrupt': <type 'exceptions.KeyboardInterrupt'>, 
'UserWarning': <type 'exceptions.UserWarning'>, 
'filter': <built-in function filter>, 
'range': <built-in function range>, 
'staticmethod': <type 'staticmethod'>, 
'SystemError': <type 'exceptions.SystemError'>, 
'BaseException': <type 'exceptions.BaseException'>, 
'pow': <built-in function pow>, 
'RuntimeError': <type 'exceptions.RuntimeError'>, 
'float': <type 'float'>, 
'MemoryError': <type 'exceptions.MemoryError'>, 
'StopIteration': <type 'exceptions.StopIteration'>, 
'globals': <built-in function globals>, 
'divmod': <built-in function divmod>, 
'enumerate': <type 'enumerate'>, 
'apply': <built-in function apply>, 
'LookupError': <type 'exceptions.LookupError'>, 
'open': <built-in function open>, 
'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 
'basestring': <type 'basestring'>, 
'UnicodeError': <type 'exceptions.UnicodeError'>, 
'zip': <built-in function zip>, 
'hex': <built-in function hex>, 
'long': <type 'long'>, 
'next': <built-in function next>, 
'ImportError': <type 'exceptions.ImportError'>, 
'chr': <built-in function chr>, 
'xrange': <type 'xrange'>, 
'type': <type 'type'>, 
'__doc__': "Ellipsis represents `...' in slices.", 
'Exception': <type 'exceptions.Exception'>, 
'tuple': <type 'tuple'>, 
'UnicodeTranslateError': <type 'exceptions.UnicodeTranslateError'>, 
'reversed': <type 'reversed'>, 
'UnicodeEncodeError': <type 'exceptions.UnicodeEncodeError'>, 
'IOError': <type 'exceptions.IOError'>, 
'hasattr': <built-in function hasattr>, 
'delattr': <built-in function delattr>, 
'setattr': <built-in function setattr>, 
'raw_input': <built-in function raw_input>, 
'SyntaxWarning': <type 'exceptions.SyntaxWarning'>, 
'compile': <built-in function compile>, 
'ArithmeticError': <type 'exceptions.ArithmeticError'>, 
'str': <type 'str'>, 
'property': <type 'property'>, 
'GeneratorExit': <type 'exceptions.GeneratorExit'>, 
'int': <type 'int'>, 
'__import__': <built-in function __import__>, 
'KeyError': <type 'exceptions.KeyError'>, 
'coerce': <built-in function coerce>, 
'PendingDeprecationWarning': <type 'exceptions.PendingDeprecationWarning'>, 
'file': <type 'file'>, 
'EnvironmentError': <type 'exceptions.EnvironmentError'>, 
'unichr': <built-in function unichr>, 
'id': <built-in function id>, 
'OSError': <type 'exceptions.OSError'>, 
'DeprecationWarning': <type 'exceptions.DeprecationWarning'>, 
'min': <built-in function min>, 
'UnicodeWarning': <type 'exceptions.UnicodeWarning'>, 
'execfile': <built-in function execfile>, 
'any': <built-in function any>, 
'complex': <type 'complex'>, 
'bool': <type 'bool'>, 
'ValueError': <type 'exceptions.ValueError'>, 
'NotImplemented': NotImplemented, 
'map': <built-in function map>, 
'buffer': <type 'buffer'>, 
'max': <built-in function max>, 
'object': <type 'object'>, 
'TabError': <type 'exceptions.TabError'>, 
'callable': <built-in function callable>, 
'ZeroDivisionError': <type 'exceptions.ZeroDivisionError'>, 
'eval': <built-in function eval>, 
'__debug__': True, 
'IndentationError': <type 'exceptions.IndentationError'>, 
'AssertionError': <type 'exceptions.AssertionError'>, 
'classmethod': <type 'classmethod'>, 
'UnboundLocalError': <type 'exceptions.UnboundLocalError'>, 
'NotImplementedError': <type 'exceptions.NotImplementedError'>, 
'AttributeError': <type 'exceptions.AttributeError'>, 
'OverflowError': <type 'exceptions.OverflowError'>}, 
'__file__': '/home/hadoop/synbot/synbot_env.pyc', 
'sys': <module 'sys' (built-in)>, 
'chk_cluster_apps': <function chk_cluster_apps at 0x2b0ded8>, 
'codecs': <module 'codecs' from '/usr/lib/python2.7/codecs.pyc'>, 
'__name__': 'synbot_env', 
'logging': <module 'logging' from '/usr/lib/python2.7/logging/__init__.pyc'>, 
'get_synbot_ini': <function get_synbot_ini at 0x2b0dc80>, 
'ConfigParser': <module 'ConfigParser' from '/usr/lib/python2.7/ConfigParser.pyc'>, 
'synbotenv': <class 'synbot_env.synbotenv'>, 
'JNS_FILE': 'jns.yml', 
'parse_synbot_config': <function parse_synbot_config at 0x2b0dde8>, 
'NNS_FILE': 'nns.yml', 
'_logger': <logging.Logger object at 0x2b18090>, 
'green': <function inner at 0x2ab5578>, 
'os': <module 'os' from '/usr/lib/python2.7/os.pyc'>, 
're': <module 're' from '/usr/lib/python2.7/re.pyc'>, 
'RMS_FILE': 'rms.yml'}